version: '3'

services:
  aggregator:
    image: ghcr.io/automata-network/multi-prover-avs/aggregator:latest
    container_name: multi-prover-aggregator
    command: -c config/aggregator.json
    volumes:
      - ./config:/config
    working_dir: /

  operator:
    image: ghcr.io/automata-network/multi-prover-avs/operator:latest
    container_name: multi-prover-operator
    command: -c config/operator.json
    depends_on:
      aggregator:
        condition: service_started
    volumes:
      - ./config:/config
    working_dir: /
