version: '3'
# This file is used for building and pushing images
services:
  aggregator:
    build:
      context: .
      dockerfile: cmd/aggregator/Dockerfile
    image: ghcr.io/automata-network/multi-prover-avs/aggregator:${BUILD_TAG}
  operator:
    build:
      context: .
      dockerfile: cmd/operator/Dockerfile
    image: ghcr.io/automata-network/multi-prover-avs/operator:${BUILD_TAG}
  oprtool:
    build:
      context: .
      dockerfile: cmd/oprtool/Dockerfile
    image: ghcr.io/automata-network/multi-prover-avs/oprtool:${BUILD_TAG}
