sequenceDiagram
  autonumber
    participant O as Operator
    participant A as Aggregator
    participant EC as Eigenlayer Contracts
    participant M as Multi-prover AVS
    participant L as TEE Liveness Contract
    participant AC as Attestation Contracts
 
Note over O,L: Operator registration
O->>EC: Restake and register to Multi-prover AVS
O->>L: Operator Liveness

Note over O,AC: Operator Liveness (Periodically)
O->>L: Submit Attesatation Report with pubkey(submitLivenessProof)
L->>AC: Verify Attestation Report(verifyAttestation)
AC-->>AC: Verify MrEncalve and MrSigner
AC-->>AC: Verify QE Report
AC-->>AC: Verify Quote CertChain
AC-->>AC: Verify TCB
AC->>L: Return reportData(pubkey)
L-->>L: Mark the operator(pubkey) as attested within the liveness cycle
 

Note over O,L: Proving state
O-->>O: Fetch task and calculate inside TEE
O->>A: Provide state and signature(submitTask)
A-->>EC: Fetch pubkey by OperaterId
A->>L: Fetch operator's validity (verifyLivenessProof)
L-->>A: Operator's validity

alt Is Valid TEE Prover
A-->>A: Wait and aggregate signatures
A->>M: Submit state and aggregated signatures
else Not Valid TEE Prover
A-->>O: Reject
end