[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 50
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = false
# Override the Solidity version (this overrides `auto_detect_solc`)
#solc_version = '0.8.12'

[fmt]
contract_new_lines = true
single_line_statement_blocks = "multi"